### ISSUE TITLE
create a twitter bot 

### ISSUE THREAD

**Issue by Attupatil** [Attupatil/tweeter_bot_follower#1]

**Comment by pranav6670** [comment]
Can I work on this? Will you please elaborate on what type of bot is to be implemented?

**Comment by Attupatil** [comment]
> Can I work on this? Will you please elaborate on what type of bot is to be implemented?

Hello @pranav6670. The bot helps you to follow a person who follows you. You can implement new things or make a readme.txt/ documentation. Basically this is made for hacktoberfest soo have fun😊

**Comment by pranav6670** [comment]
Cool, I'll make a bot who will follow back all of your followers.
